"""empty message

Revision ID: 8202a2b0e79b
Revises: 
Create Date: 2024-08-24 16:39:39.202170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8202a2b0e79b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('informacoes', sa.Text(), nullable=False),
    sa.Column('jogos', sa.Text(), nullable=False),
    sa.Column('categorias', sa.Text(), nullable=False),
    sa.Column('consoles', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    # ### end Alembic commands ###
